[package]
name = "nfscrs_jni"
version = "0.1.0"
edition = "2024"

[lib]
name = "nfscrs_jni"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
nfscrs = {path = "/home/algebnaly/work/rust/nfscrs"}
